login:
    path:   /login
    defaults:   { _controller: PhilCMSBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   /logout

phil_cms:
    resource: "@PhilCMSBundle/Resources/config/routing.yml"
    prefix:   /

