# app/config/security.yml

security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path: login
                check_path: login_check
                username_parameter: login[username]
                password_parameter: login[password]
            logout:
                path:   /logout
                target: /about

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }

    providers:
        main:
            entity:
                class:      Phil\UserBundle\Entity\User
                property:   username

    encoders:
        Phil\UserBundle\Entity\User:
            algorithm:  bcrypt
            cost:       15