# app/config/security.yml

security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path: login
                check_path: login_check
                username_parameter: login[username]
                password_parameter: login[password]
                csrf_parameter: login[_token]
            logout:
                path:   /logout
                target: /
            remember_me:
                key:    "Ov757K1#V~I}z-CR43c7~mx55B&8Qq"
                lifetime:   2592000 # a month in seconds
                remember_me_parameter:  login[rememberMe]

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user/confirm.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resendActivation, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/changepassword, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/user, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        main:
            entity:
                class:      Phil\UserBundle\Entity\User
                property:   username

    encoders:
        Phil\UserBundle\Entity\User:
            algorithm:  bcrypt
            cost:       15