# src/Phil/UserBundle/Resources/routing.yml
login:
    path:   /login
    defaults:   { _controller: PhilUserBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   /logout

user_register:
    path:   /register
    defaults: { _controller: PhilUserBundle:User:register }

user_create:
    path:   /register/create
    defaults: { _controller: PhilUserBundle:User:create }

user_update:
    path:   /user
    defaults:   { _controller: PhilUserBundle:User:update }

user_changepassword:
    path:   /user/changepassword
    defaults:   { _controller: PhilUserBundle:User:changePassword }

user_activate:
    path:   /user/confirm/{activationCode}
    defaults:   { _controller: PhilUserBundle:User:activateUser, activationCode: null }

user_resendActivation:
    path:   /user/resendActivation
    defaults:   { _controller: PhilUserBundle:User:resendActivation }