# src/Phil/UserBundle/Resources/routing.yml
login:
    path:   /user/login
    defaults:   { _controller: PhilUserBundle:Login:login }

login_check:
    path:   /user/login_check

logout:
    path:   /user/logout

user_register:
    path:   /user/register
    defaults: { _controller: PhilUserBundle:Register:create }

user_update:
    path:   /user
    defaults:   { _controller: PhilUserBundle:User:update }

user_changepassword:
    path:   /user/changepassword
    defaults:   { _controller: PhilUserBundle:User:changePassword }

user_confirm:
    path:   /user/confirm
    defaults:   { _controller: PhilUserBundle:Activate:activate, activationCode: null }

user_activate:
    path:   /user/confirm/{activationCode}
    defaults:   { _controller: PhilUserBundle:Activate:activate, activationCode: null }

user_resendActivation:
    path:   /user/resendActivation
    defaults:   { _controller: PhilUserBundle:Activate:resend }

user_forgotPassword:
    path:   /user/forgotPassword
    defaults:   { _controller: PhilUserBundle:ForgotPassword:email }

user_forgotPasswordReset:
    path:   /user/forgotPasswordReset/{resetCode}
    defaults:   { _controller: PhilUserBundle:ForgotPassword:reset }