parameters:
#    phil_user.example.class: Phil\UserBundle\Example

services:
#    phil_user.example:
#        class: %phil_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
