# src/Blogger/BlogBundle/Resources/config/routing.yml
PhilCMSBundle_content_about:
    pattern:  /about
    defaults: { _controller: PhilCMSBundle:Content:about }
    requirements:
        _method:  GET

PhilCMSBundle_content_show:
    pattern:  /{slug}
    defaults: { _controller: PhilCMSBundle:Content:show }
    requirements:
        _method:  GET
